"""empty message

Revision ID: 115c8ff10953
Revises: 6e2e693305e0
Create Date: 2025-04-24 21:38:32.834554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115c8ff10953'
down_revision = '6e2e693305e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('course', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relevant_course_work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracurriculars', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('extracurriculars')
        batch_op.drop_column('relevant_course_work')
        batch_op.drop_column('duration')
        batch_op.drop_column('course')
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
