"""empty message

Revision ID: 345a1f0fc72d
Revises: f9948b4a51e5
Create Date: 2025-03-27 16:40:02.260558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345a1f0fc72d'
down_revision = 'f9948b4a51e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username_projectname', ['username', 'projectname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username_projectname', type_='unique')

    # ### end Alembic commands ###
