"""empty message

Revision ID: 6e2e693305e0
Revises: e52ee508d4e5
Create Date: 2025-04-24 21:24:29.348588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2e693305e0'
down_revision = 'e52ee508d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('programming_languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('libraries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tools', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tools')
        batch_op.drop_column('libraries')
        batch_op.drop_column('programming_languages')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
