"""Initial migration

Revision ID: ac1b126527ab
Revises: 
Create Date: 2025-09-16 12:55:50.208351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1b126527ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('projectname', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bulletpoints', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('username', 'projectname', name='uq_username_projectname')
    )
    op.create_table('users',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('github', sa.Text(), nullable=True),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('programming_languages', sa.Text(), nullable=True),
    sa.Column('libraries', sa.Text(), nullable=True),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('course', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('extracurriculars', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
